---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# nmareporting

<!-- badges: start -->
<!-- badges: end -->

`nmareporting::`'s objective is a living package and website that provides a collaborative open resource for practical toolchains to report Bayesian network meta-analyses in R. Included is a suite of R functions from packages such as multinma:: and nmathresh::, as well as providing scope for custom functions for specific use cases. Vignettes provided on the associated site give guidance for reporting for different scientific reports, such as Cochrane. Anticipating the adoption of threshold analysis, tools are provided for practitioners to augment standard sensitivity reporting. Reporting model results to stakeholders from diverse backgrounds and disciplines by particular bodies’ protocols is a key feature of evidence synthesis. nmareporting:: explores a template for collaborative and open development of practical toolchain walkthroughs that address specific scientific protocols. In addition to the intrinsic value for reporting network meta-analyses, nmareporting:: is also a case study in how we can bring together practitioners and stakeholders from different scientific organisations to collaborate on an open, shared tool for evidence synthesis.   

## computational waystation

A great deal of thought goes into packages for general release on, say, CRAN. 

There are some problems that are best not hidden within functions, but shown as toolchain walkthroughs, and some problems are so widely encountered that functions will be of great use to the research community. It is hard for any one person to know what is required. 

Providing a computational waystation for collaborative open science on the problem enables researchers to share solutions, and identify the boundaries of what should be functionalised. This research compendium comprises:

- a website with toolchain walkthroughs and vignettes
- a package with extension functions for network meta-analysis packages, `multinma` and `nmathresh`, others, as required
- a one-stop shop for Cochrane researchers reporting network meta-analyses
- an open source repository with problems outlined in issue forums for discussion and project management

At this point, this package is not definitive, as with CRAN, but seeks instead to provide a place for development and discussion amongst R programmers reporting Cochrane network meta-analses.

## Status

In early development/design.

## Development plan

### Cochrane example 

`parkinsons` dataset

- [ ] toolchain walkthrough
- [ ] threshold analysis

### More examples for Cochrane

### Campbell and others 

- [ ] Investigate reporting standards MECIR / MECCIR (yes, both, Neal says)

### Templates

### Cochrane

- [ ] slides

## Shiny



### Others



## Installation

<!-- You can install  -->
<!-- the released version of nmareporting from [CRAN](https://CRAN.R-project.org) with: -->
<!-- ``` r -->
<!-- install.packages("nmareporting") -->
<!-- ``` -->
<!-- And  -->
You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("softloud/nmareporting")
```
